# Generated by Django 4.2.30 on 2026-05-28 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_vendorprofile_optional_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='business_hours',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='category',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
