# Generated by Django 4.2.30 on 2026-05-31 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0007_add_payout_reference_and_promptpay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='confirmation_pin_hash',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('PENDING_PAYMENT', 'Pending payment'), ('PAID', 'Paid'), ('PREPARING', 'Preparing'), ('READY_FOR_PICKUP', 'Ready for pickup'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled'), ('pending', 'Pending'), ('paid', 'Paid'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='PENDING_PAYMENT', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('FAILED', 'Failed'), ('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='payout',
            name='payout_method',
            field=models.CharField(choices=[('SIMULATED', 'Simulated'), ('PROMPTPAY', 'PromptPay'), ('BANK_TRANSFER', 'Bank transfer')], default='SIMULATED', max_length=20),
        ),
        migrations.AlterField(
            model_name='payout',
            name='promptpay_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='payout',
            name='reference_number',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='payout',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='payout_schedule',
            field=models.CharField(choices=[('HOURLY', 'Hourly'), ('DAILY', 'Daily'), ('EVERY_3_DAYS', 'Every 3 days'), ('WEEKLY', 'Weekly')], default='HOURLY', max_length=20),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='promptpay_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
