# Generated by Django 4.2.30 on 2026-05-31 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0009_add_payout_transfer_fields'),
        ('marketplace', '0009_add_promptpay_qr_fields'),
    ]

    operations = [
    ]
